name: Juste un simple GitHub Action 

on: [push, pull_request]

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher un message
        run: echo "GitHub Actions fonctionne chez moi comme dhab!" 


~
